Zach_BugTracker/Models/TicketComments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Zach_BugTracker.Models
{
    public class TicketComments
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
        public int TicketId { get; set; }
        public string UserId { get; set; }

        public virtual Ticket Ticket { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

Zach_BugTracker/Controllers/TicketCommentsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zach_BugTracker.Models;

namespace Zach_BugTracker.Controllers
{
    [Authorize]
    [RequireHttps]

    public class TicketCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TicketComments
        [Authorize]
        public ActionResult Index()
        {
            var ticketComments = db.TicketComments.Include(t => t.Ticket).Include(t => t.User);
            return View(ticketComments.ToList());
        }

        // GET: TicketComments/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            return View(ticketComments);
        }

        // GET: TicketComments/Create

        [Authorize(Roles = ("Submitter, Developer, Project_Manager"))]
        public ActionResult Create()
        {
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }

        // POST: TicketComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Comment,Created,Updated,TicketId,UserId")] TicketComments ticketComments)
        {
            if (ModelState.IsValid)
            {
                ticketComments.UserId = User.Identity.GetUserId();
                ticketComments.Created = DateTime.Now;
                db.TicketComments.Add(ticketComments);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = ticketComments.TicketId });
            }

            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", ticketComments.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", ticketComments.UserId);
            return View(ticketComments);
        }

        // GET: TicketComments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", ticketComments.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", ticketComments.UserId);
            return View(ticketComments);
        }

        // POST: TicketComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Comment,Created,TicketId,UserId,Updated")] TicketComments ticketComments)
        {
            if (ModelState.IsValid)
            {
                ticketComments.Updated = DateTime.Now;
                db.Entry(ticketComments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "SubmitterId", ticketComments.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketComments.UserId);
            return View(ticketComments);
        }

        // GET: TicketComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketComments ticketComments = db.TicketComments.Find(id);
            if (ticketComments == null)
            {
                return HttpNotFound();
            }
            return View(ticketComments);
        }

        // POST: TicketComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TicketComments ticketComments = db.TicketComments.Find(id);
            db.TicketComments.Remove(ticketComments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Zach_BugTracker/Views/TicketComments/Create.cshtml
@model Zach_BugTracker.Models.TicketComments

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TicketComments</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zach_BugTracker/Views/TicketComments/Delete.cshtml
@model Zach_BugTracker.Models.TicketComments

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TicketComments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ticket.SubmitterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.SubmitterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Zach_BugTracker/Views/TicketComments/Details.cshtml
@model Zach_BugTracker.Models.TicketComments

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TicketComments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ticket.SubmitterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Submitter.FullName)
        </dd>

        <dt>
            @Html.DisplayName("Comment Created By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Zach_BugTracker/Views/TicketComments/Edit.cshtml
@model Zach_BugTracker.Models.TicketComments

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.UserId)
    
    <div class="form-horizontal">
        <h4>TicketComments</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zach_BugTracker/Views/TicketComments/Index.cshtml
@model IEnumerable<Zach_BugTracker.Models.TicketComments>

@{
    ViewBag.Title = "Index";
}





<!--=====================================================================================================-->

<div class="admin-dashone-data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline8-list shadow-reset">
                    <div class="sparkline8-hd">
                        <div class="main-sparkline8-hd">
                            <h1>Ticket Comments</h1>
                            <div class="sparkline8-outline-icon">
                                <span class="sparkline8-collapse-link"><i class="fa fa-chevron-up"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="sparkline8-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">

                            <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="id"> @Html.DisplayNameFor(model => model.TicketId)</th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Ticket.SubmitterId)
                                        </th>
                                        <th>
                                            @Html.DisplayName("Comment By")
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Comment)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Created)
                                        </th>

                                        <th data-field="action">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <!--ForEach goes here-->
                                    @foreach (var item in Model.OrderByDescending(c => c.Created))
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.TicketId)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Ticket.Submitter.FullName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.User.FullName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Comment)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Created)
                                            </td>
                                            <td>
                                                <button class="btn btn-white btn-action btn-xs"><i class="fa fa-folder"></i> @Html.ActionLink("Details", "Details", "Tickets", new { id = item.Ticket.Id }, new { })</button>


                                                <button class="btn btn-white btn-action btn-xs" href="#" data-toggle="modal" data-target="#WarningModalhdbgcl-@item.Id"><i class="fa fa-folder"></i>Delete</button>

                                                @*<button class="btn btn-white btn-action btn-xs"><i class="fa fa-folder"></i> @Html.ActionLink("Delete", "Delete", new { id = item.Id })</button>*@
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>
                            <br />

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<br />


<div class="row" align="center">
    <h4 style="font:oblique">
        | @Html.ActionLink("Return To My Tickects", "Index", "Tickets") |
    </h4>
</div>

<br />


<!--===Delete Modal===============================================================================================================================================-->

@foreach (var item in Model.OrderByDescending(c => c.Created))
{
    <div id="WarningModalhdbgcl-@item.Id" class="modal modal-adminpro-general Customwidth-popup-WarningModal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header header-color-modal bg-color-3">
                    <h4 class="modal-title">Delete Ticket Comment?</h4>
                    <div class="modal-close-area modal-close-df">
                        <a class="close" data-dismiss="modal" href="#"><i class="fa fa-close"></i></a>
                    </div>
                </div>
                <div class="modal-body">
                    <span class="adminpro-icon adminpro-warning-danger modal-check-pro information-icon-pro"></span>
                    <h2>Warning!</h2>
                    <p>Are you sure you want to delete this Comment?</p>
                </div>
                <div class="modal-footer">
                    <a data-dismiss="modal" href="#">Cancel</a>



                    @using (Html.BeginForm("Delete", "TicketComments", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        @Html.Hidden("Id", item.Id)
                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" />

                        </div>
                    }



                </div>
            </div>
        </div>
    </div>
}
<!--===Delete Modal===============================================================================================================================================-->